### ISSUE TITLE
Dockerfile incomplete

### ISSUE THREAD

**Issue by liepaja** [ncarlier/kong-integration-samples#1]
Was not able to `make with-keycloak build deploy`.
Few more packages were needed:
```
RUN yum install -y openssl-devel gcc
```

**Comment by liepaja** [comment]
Also kong admin is not exposed outside the container. Config file needs to be edited and localhost replaced with 0.0.0.0.

**Comment by ncarlier** [comment]
New Dockerfile fixed that.
Thanks a lot for the issue report!
