### ISSUE TITLE
howto-kong_with_keycloak -> Can you explain that?

### ISSUE THREAD

**Issue by TDFS-Dom** [ncarlier/kong-integration-samples#2]
https://ncarlier.gitbooks.io/oss-api-management/content/howto-kong_with_keycloak.html
I don't know validation 
1.Keycloak: generate token
2. Send token to Kong? I don't know check token in Kong. Please help me>?

**Comment by ncarlier** [comment]
Hi,
I don't understand what your problem is? Can you be more specific, please?
Are you trying to use the OIDC Kong plugin or the JWT Kong plugin?

**Comment by TDFS-Dom** [comment]
that task i want validate token from keycloak to kong and redirect with rule of keycloak for Kong

**Comment by ncarlier** [comment]
To make Kong validate the JWT issued by Keycloak you can use either a secret or asymmetric key. If you use a secret key, you must share it between the two services.
If you use an asymmetric key, you must provide the public key to Kong to validate the token.

With the JWT plugin, this redirection have to be handled by the client. If the API returns a 401 or 403 response (from Kong) then your client have to redirect to Keycloak by itself. If you are using a JS client you can use the JS Keycloak adapter to help you to handle this.

If you want to be redirected from Kong to Keycloak then you have to use the OpenID Connect plugin.
