### ISSUE TITLE
get error when setting up kong with ELK

### ISSUE THREAD

**Issue by nanhapy** [ncarlier/kong-integration-samples#5]
Hi,
When I ran `make logs service=elasticsearch`, I got a error `make: *** No rule to make target 'logs'.  Stop.`.
Did I miss something?

**Comment by ncarlier** [comment]
Oups ! I accidentally removed the task from the Makefile. I will fix that. It's only an alias. So you can also use: `make compose-logs service=elasticsearch`.
Thank you for the report.

**Comment by ncarlier** [comment]
I put the rule back on.
